# Generated by Django 4.2.5 on 2024-01-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
