# Generated by Django 4.2.5 on 2024-01-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_phonenumber_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='number',
            new_name='phone_number',
        ),
    ]
